version: '3.8'

services:
  app:
    image: login-api
    container_name: Login-API_container
    restart: always
    environment:
      # MongoDB Atlas connection string; note that Atlas is managed externally.

      SPRING_PROFILES_ACTIVE: prod
      # Example JWT secret (ensure you secure and manage this appropriately)

    ports:
      - "8081:8080"
    build:
      context: .
      dockerfile: Dockerfile
